# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb57d3d8e95546bac774b4a80c4789d15c5720d1e5ea5b05dc7369b0f82b584938c63dea374cb8c11802708247091e1d498c44cadfecdd3d4e1fb8a3c4c131b5

test:
  secret_key_base: e7b978b72911189e6ed3abcd7b8bb36db7cb753cd98d7373bbca824e0dea979f57237110f7652eb7f3ce9eea48ab5c0429b4c858bde9630aac87a2675b8bcca3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
